const wholeStack = [
  {tagName: 'Front-end', color: '#AACFF2', name: 'frontEnd'},
  {tagName: 'Back-end', color: '#FFE58A', name: 'backEnd'},
  {tagName: 'Design', color: '#FBE1F8', name: 'design'},
  {tagName: 'Spring', color: '#C5F8C7', name: 'spring'},
  {tagName: 'Django', color: '#93C59B', name: 'django'},
  {tagName: 'Flask', color: '#ACACB4', name: 'flask'},
  {tagName: 'Node.js', color: '#D5F6C1', name: 'nodeJs'},
  {tagName: 'React', color: '#D0FDFD', name: 'react'},
  {tagName: 'Vue', color: '#B4E8D2', name: 'vue'},
  {tagName: 'Android', color: '#AFF2AA', name: 'android'},
  {tagName: 'iOS', color: '#FFBBB7', name: 'ios'},
  {tagName: 'Angular', color: '#ECA0A0', name: 'angular'},
  {tagName: 'Kotlin', color: '#FBCDB9', name: 'kotlin'},
  {tagName: 'Swift', color: '#FFDEB7', name: 'swift'},
  {tagName: 'Python', color: '#C0CCF8', name: 'python'},
  {tagName: 'Java', color: '#F4D8D8', name: 'java'},
  {tagName: 'Javascript', color: '#FFF38A', name: 'javascript'},
  {tagName: 'Typescript', color: '#C9E3FB', name: 'typescript'},
  {tagName: 'HTML/CSS', color: '#EDE4FF', name: 'htmlCss'},
  {tagName: 'Go', color: '#C1EDF6', name: 'go'},
  {tagName: 'C/C++', color: '#DEE7FE', name: 'cCpp'},
  {tagName: 'C#', color: '#CAB7FF', name: 'cCsharp'},
  {tagName: 'Firebase', color: '#FFEDAE', name: 'firebase'},
  {tagName: 'AWS', color: '#F8C488', name: 'aws'},
  {tagName: 'GCP', color: '#F9E686', name: 'gcp'},
  {tagName: 'Git', color: '#C1D2ED', name: 'git'},
  {tagName: 'Figma', color: '#C1B7FF', name: 'figma'},
  {tagName: 'Sketch', color: '#FFF9C3', name: 'sketch'},
  {tagName: 'AdobeXD', color: '#FCCAEE', name: 'adobeXD'},
  {tagName: 'Photoshop', color: '#C9E3FB', name: 'photoshop'},
  {tagName: 'Illustrator', color: '#CFC3AC', name: 'illustrator'},
  {tagName: 'etc', color: '#5C5C5C', name: 'etc'},
];

const stackNames = wholeStack.map(a => a.name);

export {wholeStack,stackNames};